### ISSUE TITLE
Saving pointnet model fails

### ISSUE THREAD

**Issue by xMartin** [Welthungerhilfe/cgm-ml#14]
In the notebook "train_on_dataset":
```
save_model_and_history(model_pointnet, history, "pointnet")
TypeError: can't pickle _thread.RLock objects
```
 - Saving voxnet works
 - Open issue: https://github.com/keras-team/keras/issues/8343
 - No workaround currently (this doesn't work: https://stackoverflow.com/a/47952913)

Environment:
 - macOS 10.13
 - Python 3.6
 - Keras 2.2.2
 - tensorflow 1.10.0

**Comment by AI-Guru** [comment]
Bummer.

Implemented workaround: Try to save the whole model. Could fail. Also save the model's weights. That always works.

If so you have to load the weights like this:

`
model = modelutils.create_point_net(...)
model.load_weights(weights_path
`
