### ISSUE TITLE
Use logging instead of print statements

### ISSUE THREAD

**Issue by markus-hinsche** [Welthungerhilfe/cgm-ml#148]
Use 5 python log levels explained in https://docs.python.org/3/howto/logging.html

Currently we use `print("abc")` statements, those can be replaced with `logger.INFO("abc")`

Acceptance Criteria:
- logs should be seen in local development, e.g. when running `src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py`
- logs should be seen during model training on a cluster
- logs should include the timestamp and path to the module (probably this is the default logging formatting)

Feel free to check how other projects make use of logging e.g. https://github.com/scikit-learn/scikit-learn/search?q=logging

**Comment by prajurock** [comment]
can we close this issue? @jasminziegler ?

**Comment by jasminziegler** [comment]
@prajurock def yes! Sry forgot to do it
