### ISSUE TITLE
user onboarding with baseline notebooks

### ISSUE THREAD

**Issue by mmatiaschek** [Welthungerhilfe/cgm-ml#23]
As a data scientist new to the project i want a quick (30 minute) introduction to the topic through Jupyter Notebooks in order to understand the data and the task at hand and start experimenting.

- [x] Create a directory "skel" with the following notebooks that is given a new user additional to the ETL data.

- [x] Install dependencies and test server
- [x] Load and visualize point clouds from pcd files
- [x] Load and visualize test and validation targets (y) from DataGenerator
- [x] Load and visualize 2D/3D (x) data from DataGenerator
- [x] Train VoxNet (test - default only 3 epochs?)
- [x] Train PointCNN (test - default only 3 epochs?)
- [x] Train 2D Depth Net (test - default only 3 epochs?)
- [x] Evaluate trained nets
- [ ] Subdirectory examples
    - segmentation and 
    - human pose prediction
    - ...

**Comment by AI-Guru** [comment]
Can we close this? 

Segmentation and human-pose-prediction seems to be a separate user-story.
