### ISSUE TITLE
etl: easier matching of scan and manual measure

### ISSUE THREAD

**Issue by mmatiaschek** [Welthungerhilfe/cgm-ml#27]
use age (in days)
```
  "age": {
    "type": "number",
    "value": 558
  },
```

**Comment by AI-Guru** [comment]
What is the task here? Please clarify.

**Comment by mmatiaschek** [comment]
currently we are matching scan (!=manual) to manual measurements through an error prone process of checking if the timestamps are within an interval. That should not be necessary, as each measure actually contains the age of the child in days. 1 to 1 matching should be possible and would probably yield a better ETL result --> more scans with ground truth.

**Comment by AI-Guru** [comment]
Thanks for the clarification. Now it makes sense.

**Comment by AI-Guru** [comment]
If I get you right... 

The manual measurements and the automatic ones both contain the age.

Currently the ETL finds the matching data via comparing timestamps. The timestamp of the media is the name of the folder, e.g. 1530772081539 in 
/srv/data/storage/person/SAM-GOV-041/measurements/1530772081539
The timestamp of the manual measurement is in the JSONs.
For example: /srv/data/db/persons/6bc426047bfb3966_prajapat_1540443651487_m0ul16vI2SWQDHPD/measures/6bc426047bfb3966_measure_1540443713379_fTayJ3SF9rIi6gas/6bc426047bfb3966_measure_1540443713379_fTayJ3SF9rIi6gas.json

Here we use a heuristic.

BUT. If I would get the age from a automatic measurement JSON somewhere in /srv/data/db, how would I get the age in the media somewhere in /srv/data/storage/person? 

I do not understand your idea of matching via age.

Please clarify further!

Note: For a future release you should directly relate the automatic measurements with their media using database-ids or something similar. Captain Hindsight in action :D

**Comment by AI-Guru** [comment]
Okay. Never mind :D
