### ISSUE TITLE
EDA notebook round(age) should round down

### ISSUE THREAD

**Issue by markus-hinsche** [Welthungerhilfe/cgm-ml#336]
Task:
- use floor(age) instead round(age)

**Comment by jasminziegler** [comment]
@markus-hinsche I thought I understood the intention behind this but now I'm not sure anymore when thinking about it again.
Why is floor the better option here?

**Comment by markus-hinsche** [comment]
Let me try to explain using an example.
1. When somebody is 600 days old, people usually say he is 1 year old, i.e. his 2nd birthday is yet to come. 
2. When we round to the next integer, we would say that this 600-days-old child is 2 years old. 

Does that make sense?

**Comment by jasminziegler** [comment]
ahhh sure! got it now. thanks :-)

**Comment by markus-hinsche** [comment]
In order to finish this, we should update the other EDA notebooks. Currently different rounding techniques are used in different notebooks

**Comment by jasminziegler** [comment]
meaning to run all of them once and push the updates results?
