### ISSUE TITLE
Ensure depthmap toolkit works for lenovo

### ISSUE THREAD

**Issue by markus-hinsche** [Welthungerhilfe/cgm-ml#411]
The code doesn't currently use the first sensor.

This could be a reason why the toolkit misbehaves for Lenovo scans. 

(CC @lvonasek)

**Comment by lvonasek** [comment]
The Lenovo Phab 2 Pro device is deprecated from 2017, we are going to stop supporting it soon (dropping support for Lenovo with release of cgm-scanner 6.0)
