### ISSUE TITLE
Fix ml-api version hack

### ISSUE THREAD

**Issue by markus-hinsche** [Welthungerhilfe/cgm-ml#421]
We temporarily introduced a hack here: https://github.com/Welthungerhilfe/cgm-ml/blob/main/src/data_utils/dataset_generation_databricks/databricks_dataset_creation.py#L108-L111

This should be resolved, e.g. by adding a column to a SQL table

**Comment by markus-hinsche** [comment]
I think this is resolved now, right? @shanky0009

**Comment by shanky0009** [comment]
yes, we can close it
